server.port: 9040
spring:
    profiles:
      active: local
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;mode=MySQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
      validationQuery: SELECT 1
      platform: h2
    h2:
       console:
          enabled: true
          path: /console
    jpa:
      hibernate:
        ddl-auto: create
        naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl